### ISSUE TITLE
Missing argument get_sample function

### ISSUE THREAD

**Issue by Mitchdev24** [maltiverse/python-maltiverse#11]
Hello Maltiverse team,

I have found a little bug on `Maltiverse.sample_get` method, after getting the function from the dictionary `mapping`, the argument sample is not going through the `sample_get_by_*` methods. Here is the original code: 

```python
def sample_get(self, sample, algorithm="sha256"):
        """Requests a sample"""
        mapping = {
            "sha256": self.sample_get_by_sha256,
            "md5": self.sample_get_by_md5,
            "sha1": self.sample_get_by_sha1,
            "sha512": self.sample_get_by_sha512,
        }
        return mapping.get(algorithm, mapping.get("sha256"))()
```

Here is the fixed code:

```python
def sample_get(self, sample, algorithm="sha256"):
        """Requests a sample"""
        mapping = {
            "sha256": self.sample_get_by_sha256,
            "md5": self.sample_get_by_md5,
            "sha1": self.sample_get_by_sha1,
            "sha512": self.sample_get_by_sha512,
        }
        return mapping.get(algorithm, mapping.get("sha256"))(sample)
```

Please, check this out.

Regards.

**Comment by dgilm** [comment]
Hello @Mitchdev24, thanks for your report.

I think you are checking an old code version.

The code at that point looks different for the current version:
https://github.com/maltiverse/python-maltiverse/blob/master/maltiverse/maltiverse.py#L168

Best regards,

**Comment by Mitchdev24** [comment]
Hello @dgilm , thanks for your reply.

You are right, I made a mistake with the code version.
Sorry for the inconvenience.

Best regards,
