### ISSUE TITLE
sample_get_md5 hash method

### ISSUE THREAD

**Issue by k0dit** [maltiverse/python-maltiverse#3]
Hi Maltiverse Team,

in the examples of the **README** file under chapter _2.5.1 - GET_, there is an example for a **sample_get_md5** method, but the Maltiverse class does not contain such a method and also, it is not provided by the [API](https://app.swaggerhub.com/apis-docs/maltiverse/api/1.0.0-oas3#/).

**Comment by dgilm** [comment]
Implemented here: https://github.com/maltiverse/python-maltiverse/pull/8

Thanks!
