### ISSUE TITLE
jwt.DecodeError: It is required that you pass in a value for the "algorithms" argument when calling decode().

### ISSUE THREAD

**Issue by soytupadrrre** [maltiverse/python-maltiverse#6]
Hi Maltiverse Team,

Working with your Python SDK and error happened related with the JWT Token, when trying to use the login method of the Maltiverse object. Example:

```python
from maltiverse import Maltiverse
api = Maltiverse()
api.login(email="email" password="password") # Raises DecodeError

# jwt.exceptions.DecodeError: It is required that you pass in a value for the "algorithms" argument when calling decode().
```

**Comment by jlopezzarza** [comment]
Hello,

We need to upload the latest version of this repository into pipy. I'll look into it and get back to you.

Thanks for reporting!

**Comment by jlopezzarza** [comment]
Package uploaded, new version should fix your issue.

Thanks again!
Cheers,
Jorge
