### ISSUE TITLE
sample_get sha256

### ISSUE THREAD

**Issue by dream91** [maltiverse/python-maltiverse#9]
I got this error when quering hash `sample_get(hash)`
`sample_get_by_sha256() missing 1 required positional argument: 'sha256'`

when I modified sample_get in [maltiverse.py](https://github.com/maltiverse/python-maltiverse/blob/master/maltiverse/maltiverse.py)

from `return mapping.get(algorithm, mapping.get("sha256"))()`
to `return mapping.get(algorithm, mapping.get("sha256"))(sample)`

Then it works now.

Tested on `Python :: 3.6`

**Comment by dgilm** [comment]
Thanks @dream91! should be fixed by #10
